apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: w759ooz2c-python 
  janus-idp.io/tekton: w759ooz2c-python
  backstage.io/kubernetes-id: w759ooz2c-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w759ooz2c-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml